# Description:
#   name: diag name
#   sf_at: diag level where it becomes Safe Fault
#   lf_at: diag level where it becomes Latent Fault
#   spf_at: diag level where it becomes Single Point Fault
#   auto_recovery: Determines whether the system will automatically recover when it recovers from an error.
#
# Note:
# empty-value for sf_at, lf_at and spf_at is "none"
# default values are:
#   sf_at: "none"
#   lf_at: "warn"
#   spf_at: "error"
#   auto_recovery: "true"
---
/**:
  ros__parameters:
    required_modules:
      autonomous_driving:
        # control
        /autoware/control/autonomous_driving/node_alive_monitoring: default
        # /autoware/control/autonomous_driving/performance_monitoring/lane_departure: default # tmp
        /autoware/control/control_command_gate/node_alive_monitoring: default
        # localization
        /autoware/localization/node_alive_monitoring: default
        /autoware/localization/performance_monitoring/matching_score: { sf_at: "warn", lf_at: "none", spf_at: "none" }
        /autoware/localization/performance_monitoring/localization_accuracy: default
        # map
        /autoware/map/node_alive_monitoring: default
        # perception
        /autoware/perception/node_alive_monitoring: default
        # planning
        /autoware/planning/node_alive_monitoring: default
        /autoware/planning/performance_monitoring/trajectory_validation: default
        # sensing
        # /autoware/sensing/node_alive_monitoring: default
        /autoware/sensing/lidar/hesai/health_monitoring: default
        /autoware/sensing/imu/node_alive_monitoring: default
        # system
        /autoware/system/node_alive_monitoring: default
        /autoware/system/emergency_stop_operation: default
        /autoware/system/service_log_checker: { sf_at: "warn", lf_at: "none", spf_at: "none" }
        /autoware/system/resource_monitoring: { sf_at: "warn", lf_at: "none", spf_at: "none" }
        /autoware/system/debug_data_logger/storage_error: default
        /autoware/system/bluetooth_monitor: { sf_at: "none", lf_at: "none", spf_at: "warn" }
        # vehicle
        /autoware/vehicle/node_alive_monitoring: default
        /autoware/vehicle/vehicle_errors/lsdb_errors: default
        /autoware/vehicle/vehicle_errors/fortelion_errors/non_errors: { sf_at: "warn", lf_at: "none", spf_at: "none" }
        /autoware/vehicle/vehicle_errors/fortelion_errors/recoverable_errors: default
        /autoware/vehicle/vehicle_errors/fortelion_errors/permanent_failure: default
        /autoware/vehicle/vehicle_errors/fortelion_errors/self_test_failure: default

      external_control:
        # control
        /autoware/control/control_command_gate/node_alive_monitoring: default
        /autoware/control/external_control/external_command_selector/node_alive_monitoring: default
        # system
        /autoware/system/node_alive_monitoring: default
        /autoware/system/emergency_stop_operation: default
        /autoware/system/service_log_checker: { sf_at: "warn", lf_at: "none", spf_at: "none" }
        /autoware/system/debug_data_logger/storage_error: default
        /autoware/system/bluetooth_monitor: { sf_at: "none", lf_at: "none", spf_at: "warn" }
        # vehicle
        /autoware/vehicle/node_alive_monitoring: default
        /autoware/vehicle/vehicle_errors/lsdb_errors: default
        /autoware/vehicle/vehicle_errors/fortelion_errors/non_errors: { sf_at: "warn", lf_at: "none", spf_at: "none" }
        /autoware/vehicle/vehicle_errors/fortelion_errors/recoverable_errors: default
        /autoware/vehicle/vehicle_errors/fortelion_errors/permanent_failure: default
        /autoware/vehicle/vehicle_errors/fortelion_errors/self_test_failure: default
