/**:
  ros__parameters:
    wheel_radius: 0.13
    wheel_width: 0.07
    wheel_base: 0.348 # between front wheel center and rear wheel center
    wheel_tread: 0.363 # between left wheel center and right wheel center
    front_overhang: 0.2315 # between front wheel center and vehicle front
    rear_overhang: 0.213 # between rear wheel center and vehicle rear + cover
    left_overhang: 0.1185 # between left wheel center and vehicle left
    right_overhang: 0.1185 # between right wheel center and vehicle right
    vehicle_height: 1.179 # vehicle height + sensor_kit height
    max_steer_angle: 0.70 # [rad]
