/**:
  ros__parameters:
    wheel_radius: 0.13
    wheel_width: 0.07
    wheel_base: 0.348 # between front wheel center and rear wheel center 518mm
    wheel_tread: 0.363 # between left wheel center and right wheel center 450mm
    front_overhang: 0.2315 # between front wheel center and vehicle front 168.5mm
    rear_overhang: 0.213 # between rear wheel center and vehicle rear + cover 168.5mm
    left_overhang: 0.1185 # between left wheel center and vehicle left 86mm
    right_overhang: 0.1185 # between right wheel center and vehicle right 75mm
    vehicle_height: 1.129 # vehicle height + sensor_kit height 1095mm
    max_steer_angle: 0.70 # [rad]
