/**:
  ros__parameters:
    vehicle:
      type: diagnostic_aggregator/AnalyzerGroup
      path: vehicle
      analyzers:
        vehicle_errors:
          type: diagnostic_aggregator/AnalyzerGroup
          path: vehicle_errors
          analyzers:
            lsdb_errors:
              type: diagnostic_aggregator/AnalyzerGroup
              path: lsdb_errors
              analyzers:
                internal_error:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: internal_error
                  contains: [": Internal error"]
                  timeout: 1.0
                encoder_abz_signal_error:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: encoder_abz_signal_error
                  contains: [": Encoder ABZ signal error"]
                  timeout: 1.0
                eEncoder_uvw_signal_error:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: eEncoder_uvw_signal_error
                  contains: [": Encoder UVW signal error"]
                  timeout: 1.0
                encoder_counting_error:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: encoder_counting_error
                  contains: [": Encoder counting error"]
                  timeout: 1.0
                driver_temperature_too_high:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: driver_temperature_too_high
                  contains: [": Driver temperature too high"]
                  timeout: 1.0
                driver_bus_voltage_too_high:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: driver_bus_voltage_too_high
                  contains: [": Driver bus voltage too high"]
                  timeout: 1.0
                driver_bus_voltage_too_low:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: driver_bus_voltage_too_low
                  contains: [": Driver bus voltage too low"]
                  timeout: 1.0
                driver_output_short_circuit:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: driver_output_short_circuit
                  contains: [": Driver output short-circuit"]
                  timeout: 1.0
                braking_resistor_temperature_too_high:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: braking_resistor_temperature_too_high
                  contains: [": Braking resistor temperature too high"]
                  timeout: 1.0
                following_error_over_range:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: following_error_over_range
                  contains: [": Following error over-range"]
                  timeout: 1.0
                i2t_error:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: i2t_error
                  contains: [": I²T error(Overload)"]
                  timeout: 1.0
                speed_following_error_over_range:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: speed_following_error_over_range
                  contains: [": Speed following error over-range"]
                  timeout: 1.0
                motor_temperature_too_high:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: motor_temperature_too_high
                  contains: [": Motor temperature too high"]
                  timeout: 1.0
                searching_motor_failed:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: searching_motor_failed
                  contains: [": Searching motor failed(Communication encoder)"]
                  timeout: 1.0
                communication_failed:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: communication_failed
                  contains: [": Communication failed"]
                  timeout: 1.0
            fortelion_errors:
              type: diagnostic_aggregator/AnalyzerGroup
              path: fortelion_errors
              analyzers:
                non_errors:
                  type: diagnostic_aggregator/AnalyzerGroup
                  path: non_errors
                  analyzers:
                    low_voltage:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: low_voltage
                      contains: [": Low voltage detection"]
                      timeout: 2.0
                    fully_charge:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: fully_charge
                      contains: [": Fully charge detection"]
                      timeout: 2.0
                    over_charge_cell:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: over_charge_cell
                      contains: [": Over charge cell (Recoverable)"]
                      timeout: 2.0
                recoverable_errors:
                  type: diagnostic_aggregator/AnalyzerGroup
                  path: recoverable_errors
                  analyzers:
                    over_current_discharge_65a:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: over_current_discharge_65a
                      contains: [": Over current (discharge) detection (65A)"]
                      timeout: 2.0
                    over_current_discharge_90a:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: over_current_discharge_90a
                      contains: [": Over current (discharge) detection (90A)"]
                      timeout: 2.0
                    over_current_charge_45a:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: over_current_charge_45a
                      contains: [": Over current (charge) detection (45A)"]
                      timeout: 2.0
                    over_temp_discharge:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: over_temp_discharge
                      contains: [": Over temperature (discharge) detection"]
                      timeout: 2.0
                    over_current_discharge_200a:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: over_current_discharge_200a
                      contains: [": Over current (discharge) detection (200A)"]
                      timeout: 2.0
                    over_current_discharge_110a:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: over_current_discharge_110a
                      contains: [": Over current (discharge) detection (110A)"]
                      timeout: 2.0
                    over_current_charge_65a:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: over_current_charge_65a
                      contains: [": Over current (charge) detection (65A)"]
                      timeout: 2.0
                    over_temp_charge:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: over_temp_charge
                      contains: [": Over temperature (charge) detection"]
                      timeout: 2.0
                    cell_unbalance:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: cell_unbalance
                      contains: [": Cell unbalance detection"]
                      timeout: 2.0
                permanent_failure:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: permanent_failure
                  contains: [": Permanent Failure"]
                  timeout: 2.0
                self_test_failure:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: self_test_failure
                  contains: [": Self-Test Failure"]
                  timeout: 2.0
